### PR TITLE
Add Relationship model and add relationships to Dataset model

### PR DESCRIPTION
**Pull request by spongessuck**
## Description
Addresses #131: Adds Relationship model and adds Relationships property to Dataset model.

## Questions
please answer the following questions. put x inside [ ] (e.g. [x])

### What inside?
- [ ] Bug Fixes?
- [x] New Features?
- [ ] Documentation?

### Is pull request totally generated from swagger file?
- [x] Yes.
- [ ] No, part of it is auto-generated.

### Backward compatibility break?
- [ ] Yes. Pull request breaks backward compatibility!

[Learn more about backward compatibility.](BackwardCompatibility.md)

### CODE REVIEW

**Comment by spongessuck** [comment]
Sure thing; I had no idea you could do that.

**Comment by spongessuck** [comment]
Any changes I need to make here?

**Comment by AkosLukacs** [comment]
Oh, please merge this. Relationships were announced over two years ago, but still not in the official C# api?

**Comment by spongessuck** [comment]
Looks like Relationships have been added. It'd be nice if maintainers would be more diligent in managing PRs; it looks like I'm not the only one who was waiting for this feature.

**Pull request closed without merging**
