### PR TITLE
Sample AutoRest 3.3.0 generated client with better CloudExceptions

### PR DESCRIPTION
**Pull request by mikeblakeuk**
Upgrade to latest Azure AutoRest client (using node)

### What inside?
- [x] Bug Fixes? uses latest node, autorest
- [x] New Features? Better CloudExceptions
- [x] Documentation?

### Is pull request totally generated from swagger file?
- [x] Yes.

### Backward compatibility break?
- [ ] No

### CODE REVIEW

**Comment by mikeblakeuk** [comment]
Any thoughts on this? @ali-hamud

**Comment by ali-hamud** [comment]
Thanks Mike for your contribution.
I will look into it.

**Comment by ali-hamud** [comment]
Hi Mike,

I checked your code.
it works well, but it breaks backward-compatibility, not as you marked in the description.

if you look into sdk\PowerBI.Api\Source folder, you will see that the classes are generated into different names.
AutoRest version 1.x gives different names to classes from versions 0.x
Today we use: 0.1.16

I will continue to look into it, and try to get to a good solution.
On one hand, I don't want to break all our customers with such a change. and on the other hand, I want to help you.

I will try to search a flag in AutoRest that may generate the library differently.
Do you have any other suggestions?

**Comment by mikeblakeuk** [comment]
Increment the NuGet package Major (SemVer) to show a breaking change?
Add previous model wrappers so existing clients map to the new model?
Change the name space to Microsoft.PowerBI.Api.V2.Models !?! (Not sure why the version is even in the namespace)

**Comment by ali-hamud** [comment]
Mike,

Why do use 
-CodeGenerator Azure.CSharp

and not 
-CodeGenerator CSharp?

**Comment by ali-hamud** [comment]
Btw, you can see the errors returned in Response body without your changes.

Please see:
https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app/blob/c5d97250df67cc6c369ac71a810e21e6055e1025/ProvisionSample/Program.cs
Look at line: 166. Search PBIExceptionBody

tell me if it works for you

**Comment by mikeblakeuk** [comment]
a) Azure.CSharp includes the 
`DeserializationSettings.Converters.Add(new CloudErrorJsonConverter());`
within the client
(You are also returned a AzureOperationResponse object, x-ms-client-request-id and accept-language are in the header (sent) and RequestId is populated )

I suggest you generate with and without the Azure flag and compare the outputs?
image

b) I too have written a Body to Exception converter:
https://github.com/Azure/autorest/issues/931#issuecomment-291540997
But it would be nicer if we used the generated one so the exception stack is maintained.
It would also be nice if the Azure API are consistent. Power BI is part of Azure so I would have expected to have the AutoRest Azure code base?

**Comment by ali-hamud** [comment]
Mike,
1) I don't see how this help you:
DeserializationSettings.Converters.Add(new CloudErrorJsonConverter());

PowerBI error structure is not necessarily the same structure as azure errors. and this is an answer to the second question as well. In addition, Azure and Power BI are separated services.

2) AutoRest is generic library, it should not have Power BI code.
did you checked in the code you suggested in Azure/autorest#931 (comment) ??
I believe that it's totally wrong to write Power BI error parser in AutoRest.

3) As an improvement to error handling, we may add Utility class that gives a method like:
GetPbiError, which gives an error object with error code and message (in case of error of course).

4) Generating code under different namespace could work. it will populate the SDK, but if it's necessary we will do that.

Please let me know what do you think.

**Comment by mikeblakeuk** [comment]
1. `CloudErrorJsonConverter` is what converts the response to the generic Azure exception, used by https://github.com/Microsoft/PowerBI-CSharp/pull/93/files#diff-f360ae8c166b0963d9f1d87963a56664R173.

2. I agree AutoRest is generic. My code in #931 is a suggestion that you can create your own exception handling now that the AutoRest client returns the exception messages. It previously didn't. i.e. fiddler contained data that wouldn't flow back to the client.

3. Why are the exception classes not consistent? It makes the programming API easier for the consumer. Why not use the generated exception classes instead of custom Power BI one.

4. I've not see a "v1" in a namespace before. If we opted to upgrade to a "v2", if that ever was published, it would be a large change to files that might not need changes other than using statements.

I would expect that as Power BI embedded is an Azure resource an so would have the same authentication and exception handling as other Azure clients.

I'm also happy that Power BI is treated as a non-Azure service but the generated client should throw exceptions with the messages. I would prefer if the same style was "stolen" from the Azure exception handling. e.g. using http://www.symbolsource.org/Public/Metadata/NuGet/Project/Microsoft.Rest.ClientRuntime.Azure/1.0.21/Release/.NETFramework,Version=v4.5/Microsoft.Rest.ClientRuntime.Azure/Microsoft.Rest.ClientRuntime.Azure/CloudException.cs instead of https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app/blob/3390bfeafd05e7e1bd9aa3ed461f0ab073ddf6e2/ProvisionSample/Models/PBIExceptionBody.cs

It sounds like we could regenerate the client using just CSharp and add an exception handler is of the same flavour as the one that comes with Csharp.Azure. This is why i generated using Azure, to same the copy and pasting of the exception class.

**Comment by mikeblakeuk** [comment]
image

Are there any plans to bubble up the response message into the Exception?

**Comment by ali-hamud** [comment]
I still don't understand why you don't have the response message in the exception?
the image above shows that you have it.

**Comment by mikeblakeuk** [comment]
Yes, the REAL message is in the OperationException in the Response property.
My request is that the Exception should be wrapped and the REAL error message made into a property on the Exception, so saves adding exception code within my project.

Azure services do this using 
`powerBiClient.DeserializationSettings.Converters.Add(new Microsoft.Rest.Azure.CloudErrorJsonConverter());`

https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/x-ms-pageable/example1.cs#L383

It is currently misleading that the exception is a 404 when in fact the real problem is hidden. the example above is "Feature is not available", not 404.

It will also help when logging as the REAL message will be on the exception.

Also, If i wrap and handle the exception, I will (probably) lose the stack trace.

**Comment by mikeblakeuk** [comment]
I wonder if we need AutoRest to expose and extension point https://github.com/Azure/autorest/issues/2341

**Comment by mikeblakeuk** [comment]
This is now old due to v2.
A new pull request will be raised to convert the error response body from a Json string to c# classes.

**Pull request closed without merging**
