### PR TITLE
Feature/swagger update

### PR DESCRIPTION
**Pull request by mikeblakeuk**
## Description
Regenerate model from swagger using latest autorest to get type safe enums

## Questison
please answer the following questions. put x inside [ ] (e.g. [x])

### What inside?
- [x] Bug Fixes? minor swagger json fixes
- [x] New Features?

### Is pull request totally generated from swagger file?
- [x] Yes.

### Backward compatibility break?
- [x] Yes. Pull request breaks backward compatibility!

[Learn more about backward compatibility.](BackwardCompatibility.md)

### CODE REVIEW

**Comment by mikeblakeuk** [comment]
@ali-hamud @eligr thoguhts one this?

**Comment by mikeblakeuk** [comment]
@ali-hamud @eligr I assume 3.x will use the latest AutoRest to generate Enums and code?

**Comment by mikeblakeuk** [comment]
@ali-hamud @eligr Where is the source for V3?

**Comment by mikeblakeuk** [comment]
@ali-hamud @eligr Where is the source for V3 / latest?

**Comment by laurent-mic** [comment]
This is the source for V3 / latest.

**Pull request closed without merging**
