### PR TITLE
V1.x.x

### PR DESCRIPTION
**Pull request by rebuy-lheinemann**
## Description
A few sentences describing the overall goals of the pull request's commits.

## Questison
please answer the following questions. put x inside [ ] (e.g. [x])

### What inside?
- [ ] Bug Fixes?
- [ ] New Features?
- [x] Documentation?

### Is pull request totally generated from swagger file?
- [ ] Yes.
- [ ] No, part of it is auto-generated.

### Backward compatibility break?
- [ ] Yes. Pull request breaks backward compatibility!

[Learn more about backward compatibility.](BackwardCompatibility.md)

### CODE REVIEW

**Comment by ali-hamud** [comment]
please resolve conflicts before we can merge the changes.

**Comment by mikeblakeuk** [comment]
Should this be closed?
Also, where is the 3.1-beta branch?

**Comment by ali-hamud** [comment]
Yes it should be closed. v1.x.x is not relevant anymore.
3.1-beta branch: @MahirDiab. can you please check this

**Comment by AlexRademeyer** [comment]
Hi.
Sorry, not sure where to add a comment so I am adding it here, tell me if there is a better place.
I tried using this as a custom connector with Microsoft Flow and there was a problem with the dataflows/refreshes function.
You are missing a "content type" header, so the MS Flow connector tries to use plain text which is not accepted.
I added the header so that I can choose "application/json" and now it runs successfully:

        {
            "name": "Content-Type",
            "in": "header",
            "required": false,
            "type": "string"
          }

**Comment by ali-hamud** [comment]
Closing this PR. 1.x.x is deprecated.

**Pull request closed without merging**
