### PR TITLE
Update .Net Version to 4.6

### PR DESCRIPTION
**Pull request by ali-hamud**
Update .Net Version to 4.6
Update all Nugets 
Update code to fix backward comp. braeks.

### CODE REVIEW

**Comment by obryckim** [comment]
Any ETA on when this will be pulled in and released?
Thanks!

**Comment by pavlalexandr** [comment]
You need to fix token generation method in PowerBi.Core project. 

public string Generate(string accessKey = null)
        {
            if (string.IsNullOrWhiteSpace(this.AccessKey) && accessKey == null)
            {
                throw new ArgumentNullException(nameof(accessKey));
            }

            this.ValidateToken();

            accessKey = accessKey ?? this.AccessKey;

            var key = Encoding.UTF8.GetBytes(accessKey);
            var signingCredentials = new Microsoft.IdentityModel.Tokens.SigningCredentials( new Microsoft.IdentityModel.Tokens.SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha256Signature);
            var token = new JwtSecurityToken(this.Issuer, this.Audience, this.Claims, DateTime.UtcNow, this.Expiration, signingCredentials);

            return new JwtSecurityTokenHandler().WriteToken(token);
        }
Please do so. All guys are waiting for this hotfix...

**Comment by zigzag95** [comment]
` 

			this.ValidateToken();

			accessKey = accessKey ?? this.AccessKey;
			var key = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(accessKey));
			//var key = Encoding.UTF8.GetBytes(accessKey);
			var signingCredentials = new Microsoft.IdentityModel.Tokens.SigningCredentials(key, SecurityAlgorithms.HmacSha256);
			var token = new JwtSecurityToken(this.Issuer, this.Audience, this.Claims, DateTime.UtcNow, this.Expiration, signingCredentials);

			return new JwtSecurityTokenHandler().WriteToken(token);
		}
`

**Comment by Listbd** [comment]
What assistance is needed to make this happen?

**Comment by pavlalexandr** [comment]
> What assistance is needed to make this happen?
I cloned the repository and rebuilt it manually. Just as on option for you

**Comment by ali-hamud** [comment]
Not needed anymore as we moved to Power BI Premium embedded - V2.0.0

**Pull request closed without merging**
